- .travis.yml
- README.rst
Signed-off-by: Daira Hopwood <daira@jacaranda.org>
> Recommend six 1.9.0, and have Travis-CI test using that version.

- CHANGELOG.rst
- docs/fixers.rst
- libmodernize/fixes/__init__.py
- libmodernize/fixes/fix_classic_division.py
- tests/test_fix_classic_division.py
Opt-in due to changed semantics, and potential issues with objects that don't support truediv/floordiv.
Closes #17.
Author: Brett Cannon <brett@python.org>
Signed-off-by: Daira Hopwood <daira@jacaranda.org>
> Add a classic_division fixer.

- CHANGELOG.rst
https://pypi.python.org/pypi/modernize/0.3
https://pypi.python.org/pypi/modernize/0.4
> Add release dates to the CHANGELOG.rst restored from PyPI

- setup.py
This allows to execute tool as `python -m modernize` after installation
> Ship modernize module, solves #114

- .travis.yml
If it works, this should make test runs faster, both in terms of actual run time and queueing time for the builds.
http://docs.travis-ci.com/user/workers/container-based-infrastructure/
> Enable container-based tests on Travis

- libmodernize/fixes/fix_dict_six.py
- tests/test_fix_dict_six.py
Addresses issue #119 - it's not exactly what the author asked for, but I think it's better ;-)
For some reason, 2to3 only treats a for loop as a special context for iter* methods, so it will add a list() call to e.g. `for x in d.values()`.
> Fix transformation of non-iter dict methods in for loops

- libmodernize/__init__.py
- tests/test_fix_import.py
Addresses issue #18
Imports are also placed after any comments (such as copyright notices), to be consistent with the existing import placement in files with module docstrings.
> Import statements should be placed after the shebang.

- libmodernize/__init__.py
- tests/test_future_behaviour.py
Modernising code that did `from __future__ import (...)` was failing.
I couldn't get the test for this to fail - I'm not sure why. But this change made it work on the actual code I was testing with.
> Handle parenthesised future imports

- CHANGELOG.rst
- docs/fixers.rst
- libmodernize/fixes/__init__.py
- libmodernize/fixes/fix_unichr.py
- libmodernize/fixes/fix_unichr_type.py
- tests/test_fix_unichr_type.py
This can be trivially fixed by using the six unichr shim.
> Add a fixer for instances of `unichr`

- libmodernize/main.py
- tests/test_main.py
- tests/utils.py
This is very useful for us when using python-moderize in CI to ensure
we don't regress Python 3 compat.  Otherwise, we have to roll our own
way using git.  For example:
https://github.com/zulip/zulip/blob/master/tools/check-py3#L103
> Add a flag to python-moderinze to return a non-zero exit code if any fixers needed to be applied.

- libmodernize/fixes/__init__.py
`fix_renames` only replaces `sys.maxint` with `sys.maxsize`, which is also present in Python 2.
https://hg.python.org/cpython/file/2.7/Lib/lib2to3/fixes/fix_renames.py
> Enable `fix_renames` by default

- libmodernize/fixes/fix_imports_six.py
Everything under `urlparse` moved to `six.moves.urllib.parse`
> Automatically fix `urlparse` imports

- .travis.yml
- libmodernize/__init__.py
A modification to `is_listcomp` was necessary due to a change in cpython:
- https://github.com/python/cpython/pull/2235
Supersedes #156
> Drop python3.3, add python3.6

- libmodernize/main.py
In `2to3`, fixers are short names such as `reduce`. In python-modernize, names are long-form such as `lib2to3.fixes.fix_reduce`. This fix allows both naming conventions to be used.
Also allows fixers to be listed as comma-separated values.
Also improved output to show more detailed initialization information.
Fixes #27 #163
> Handle fixers by short name as well as long name

- libmodernize/__init__.py
- tests/test_fix_open.py
- tests/utils.py
Currently the 'absolute_import' future is added anywhere a non-future import happens. This branch removes that side-effect. The existing 'import' fixer has a very similar effect and can be directly enabled or disabled by the user.
Fixes #163 #142
> Don't add 'absolute_import' futures indiscriminately

- docs/fixers.rst
- libmodernize/main.py
This adds support for user-provided fixers in the `python-modernize` command -- or, rather, mostly, removes the blocking of their use.
I found that, when the command-line tool is invoked, the current working directory is not on the Python-path -- which means user-provided fixers are likely not to be found. I added a command-line flag to help remedy this, thinking that by default, we don't want random modules to mix into the library.
I made what I think are the relevant documentation changes, criticism very welcome there. English is not my native language.
I looked for tests, and found essentially none for similar functionality of the main module, so I skipped those; if you think it necessary, I'll add them.
I also included a separate commit which prevents a single `-f` option from …
> Support user-provided fixers (fixes #166)

- modernize.py
- This PR updates `modernize.py` so that `python -m modernize` returns the same exit code as invoking `libmodernize.main` directly.
Should close https://github.com/python-modernize/python-modernize/issues/171:
> I'm seeing some inconsistencies with exit codes depending on how `python-modernize` is invoked on the command line...e.g. invoking the binary directly like `python-modernize` yields a different error code than `python -m modernize`:
> ```
> $ python-modernize this-file-does-not-exist.py
> etc.
> RefactoringTool: No files need to be modified.
> RefactoringTool: There was 1 error:
> RefactoringTool: Can't open this-file-does-not-exist.py: [Errno 2] No such file or directory: 'this-file-does-not-exist.py'
> $ echo $?
> 1
> 
> $ python -m modernize this-file-does-not-exist.py
> etc.
> …
```
> Make python -m modernize return correct exit code

- libmodernize/main.py
`python-modernize` should print a plain diff, without script info / errors
Right now when redirecting modernize results to a file (`python-modernize script.py > patch.diff`) the resulting `patch.diff` file contains some info regarding fixers and transformations used by `python-modernize` which is useless and makes a corrupted patch file.
Signed-off-by: speidy <speidy@gmail.com>
> Print fixers and used transformations to stderr

- .pre-commit-hooks.yaml
This is WIP, I wanted to get some feedback on whether this is desirable and if so where to document this :)
[pre-commit](https://github.com/pre-commit/pre-commit) is a mutli-language git hooks framework and perhaps more importantly a linter-runner framework.
This metadata makes it very easy to add `python-modernize` to a repository that's  already using the pre-commit framework.
> Add https://pre-commit.com metadata

- .github/workflows/main.yml
pre-commit will bootstrap a node environment if there isn't one there
> node shouldn't be needed

- pyproject.toml
based on the default packages that rtd installs ```/home/docs/checkouts/readthedocs.org/user_builds/ldaptor/envs/185/bin/python -m pip install --upgrade --no-cache-dir --use-feature 2020-resolver setuptools==41.0.1 docutils==0.14 mock==1.0.1 pillow==5.4.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.8.1 recommonmark==0.5.0 sphinx<2 sphinx-rtd-theme<0.5 readthedocs-sphinx-ext<1.1```
> upgrade all docs deps

- modernize/fixes/fix_itertools_six.py
There is a small typo in modernize/fixes/fix_itertools_six.py.
Should read `which` rather than `wich`.
> docs: fix simple typo, wich -> which
